### ISSUE TITLE
Specifying years of history does not work

### ISSUE THREAD

**Issue by johagg17** [synthetichealth/synthea#1064]
### What happened?

Hi! 

I am trying to generate patients with a specific number of medical years of history, but I can't get it to work. 
I tried setting the number of years in the properties file and setting it in the command line. 

When I take the difference between the START of the first admission and STOP of the last admission I get way more years of history than I specified, am I doing something wrong or misinterpreting the property "years_of_history"?

The following commands I have tried:

1. run_synthea -p 1000 -k 3diagnosis.json --exporter.years_of_history 3
2. run_synthea -p 100 --exporter.years_of_history 3

Thank you, 
Best regards :)

**Comment by jawalonoski** [comment]
Try `--exporter.years_of_history=3`

The equals sign is required.

**Comment by jawalonoski** [comment]
I'll update the documentation to correct this.

**Comment by dehall** [comment]
The equals sign shouldn't be required - if it's not present the logic will pick the next command line argument as the value of the setting.

@johagg17 The filter logic also keeps "active" items from outside the relevant date range. For example if a patient was diagnosed with Diabetes 20 years ago but the years_of_history is set to 10, that Diabetes diagnosis will still be active and included in the export. Then, because Synthea's data model revolves around the Encounter, that Encounter where the diagnosis was made will also be included even if outside the 10 year cutoff.
With this in mind, let us know if you're still seeing instances where the retained entries don't make sense.

**Comment by johagg17** [comment]
Even using --exporter.years_of_history=3 does not s

**Comment by johagg17** [comment]
Okay, thank you! :)

**Comment by jawalonoski** [comment]
Has this resolved your issue?

**Comment by johagg17** [comment]
Yes, thank you for helping me out! :)

**Comment by chaudhariatul** [comment]
## Issue reoccured with latest, 3.2.0, 3.1.1 and 3.1.0.

Version 3.0.0 generates observations with correct years and encounters are much beyond the number of years specified with `**exporter.years_of_history**`

---
Would it be possible to add a feature for `**days_of_history**` as well?
