### ISSUE TITLE
Gout CarePlan Issue

### ISSUE THREAD

**Issue by cjduffett** [synthetichealth/synthea#123]
The following error appeared during one of my FHIR validation tests:

```
RuntimeError: Target encounter Gout_Diagnosis was not processed before state Gout_CarePlan
```

Since we added the check for `concurrent_with_target_encounter` it seems we've uncovered a small issue with the `Gout` module. Should be a quick fix.

**Comment by jeffeastman** [comment]
Here's the state transition list for Gout: Note that Gout => Gout_CarePlan => Gout_Diagnosis. I believe the last two states need to be reversed, since "The CarePlanStart state must come after a target_encounter Encounter state in the module, but must have the same start time as that Encounter". Only ConditionOnset (and perhaps AllergyOnset, IDK) may refer to future encounters.

Gout [Initial [Initial]]
	Colchicine => {Uric_Acid_Reducer, }
	Delay_Until_Gout => {Gout, }
	End_Gout_Nonopioid => {End_Uric_Acid_Reducer, }
	End_Uric_Acid_Reducer => {Wait_For_Next_Gout_Attack, }
	Gout => {Gout_CarePlan, }
	Gout_CarePlan => {Gout_Diagnosis, }
	Gout_Diagnosis => {Gout_Nonopioid_Pain_Medication, }
	Gout_Nonopioid_Pain_Medication => {Colchicine, Strong_NSAID, }
	Gout_Treatment_Period => {End_Gout_Nonopioid, }
	Initial => {Delay_Until_Gout, Terminal, }
	Strong_NSAID => {Uric_Acid_Reducer, }
	Terminal => {}
	Uric_Acid_Reducer => {Gout_Treatment_Period, }
	Wait_For_Next_Gout_Attack => {Wait_For_Next_Gout_Attack, Gout_Diagnosis, }

**Comment by jeffeastman** [comment]
The above reordering fixed the issue with me.
