### ISSUE TITLE
Wellness Encounters [Record_Height [Observation]]

### ISSUE THREAD

**Issue by jeffeastman** [synthetichealth/synthea#148]
Looks to me like these ought to be VitalSign states and not Observations. According to the Wiki, only vital signs have the vital_sign field.

**Comment by jeffeastman** [comment]
Also some in metabolic_syndrome_disease and metabolic_syndrome_care

**Comment by jeffeastman** [comment]
I changed these Observations to VitalSigns, but many have no exact or range, so I assume these are not required by Synthea. I'm guessing these vitals are managed by the Ruby code and having no exact or range means to use the managed values instead?

"The VitalSign state type indicates a point in the module where a patient's vital sign is set. Vital Signs represent the physical state of the patient, in contrast to Observations which are the recording of that physical state."

**Comment by dehall** [comment]
Observations are allowed to have the vital_sign field - that indicates that instead of directly specifying a value or range of possible values, the value of the corresponding VitalSign is recorded in the Observation. You're right that the vital signs in question are managed by the ruby code (specifically  https://github.com/synthetichealth/synthea/blob/master/lib/modules/lifecycle.rb#L165 ). 

Ideally I'd like to have as many vital signs as possible represented in the GMF instead of in the ruby code, but many vital signs have complex formulas, which we haven't found a good way to represent in the GMF yet.

**Comment by jeffeastman** [comment]
Ok, I see that now. Was it there before? I can't imagine that I missed it.

**Comment by jeffeastman** [comment]
I've implemented vital_sign in Observation but now I'm finding situations where no vital sign was recorded before the observation requested it (e.g. Height). What's the recommended implementation?

**Comment by jawalonoski** [comment]
Some of the vital signs are assigned at birth so that doesn't happen in our system.

**Comment by jeffeastman** [comment]
Thanks, I do that too but I was just wanting a clarification. For signs like height and weight, I see you have assigned trajectories for them. Height levels off around 21 and weight increase slows down after then (depending upon diet and exercise risks)?

**Comment by jawalonoski** [comment]
Yes, that is right. Weight also stabilizes at age 49 then starts to decrease at 60. Those are configurable, and there are citations in the `config/synthea.yml` file.

**Comment by jeffeastman** [comment]
Closing this issue as it has been resolved
