### ISSUE TITLE
 C-CDA output patient record

### ISSUE THREAD

**Issue by filimon1** [synthetichealth/synthea#249]
What do I need to do to create the patient record in C-CDA format? I saw the instruction on https://github.com/synthetichealth/synthea "Synthea will output patient records in C-CDA (requires running instance of Mongo DB) and FHIR STU3 formats in ./output." However, I am not sure how MongoDB instance is created or runs.

Thank You so much

**Comment by dehall** [comment]
The install process for MongoDB is different depending on whether you're on Windows, Mac, or Linux.  More information on the install process is available here: https://docs.mongodb.com/manual/installation/#mongodb-community-edition


That said, I would also encourage you to take a look at the synthea_java project, which can output patients in CCDA format without the dependency on MongoDB. It's not feature-complete to the level of the ruby version, but we expect it to be there within the next month or so.
https://github.com/synthetichealth/synthea_java

In synthea_java, you can enable CCDA export by editing the properties file at `src/main/resources/synthea.properties` and setting `exporter.ccda.export = true` .  You may also want to change `generate.default_population` to a larger number, since the default is 1.
Then you run synthea_java with the command `./gradlew run`


For another alternative, depending on your requirements, you may find enough sample patients at   https://syntheticmass.mitre.org/ . We offer 1,000 sample patients in CCDA format at https://syntheticmass.mitre.org/downloads/2017_11_06/synthea_sample_data_ccda_nov2017.zip , or you can browse the individual patients in the dashboard and download them in CCDA format.

**Comment by filimon1** [comment]
@dehall Thank you so much, this is very helpful and the synthea_java seems to be working fine for now. Also, thumbs up for your quick response.
