### ISSUE TITLE
Table Based Transition

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#302]
It will be useful to have a table based transition. For example, see: https://github.com/OSEHRA/Synthetic-Patient-Data-Project

This project is attempting to create transition probabilities based on patient race, gender, and age. This creates many many states and a confusing graph. It would be simpler to create a single state with a table based transition.

For example:

`race` | `gender` | `age` | `attribute1` | ... | `attributeN` | `state1` | ... | `stateN` 
--------|-----------|------|-------------|----|-------------|----------|---|----------
`white` | `male` | `0-15` | `true` | ... | `false` | `0.8` | ... | `0.01`
`white` | `female` | `0-15` | `true` | ... | `false` | `0.7` | ... | `0.01`
`black` | `male` | `0-15` | `true` | ... | `false` | `0.5` | ... | `0.5`
`black` | `female` | `0-15` | `true` | ... | `false` | `0.6` | ... | `0.4`

The idea is that the headers are attributes to match against, and then the numbers under the headers are transition probabilities. So, in the example above, a white male aged 13 with the other attribute values would have a probability of 0.8 (or 80% chance) to transition to `state1`.

**Comment by dehall** [comment]
:+1: , especially if it can reduce to the equivalent of a switch/case statement

**Comment by dehall** [comment]
Alternative implementation proposal: add lookup tables with the ability to set one or more attributes based on that lookup table, and then use the existing "named transition" concept for transitions. There are a lot of places that lookup tables could be useful beyond just transitions (notably some of the areas we currently have hardcoded in the java code instead of in gmf modules -- vital sign ranges, calculations like the framingham points system, etc) and this would be a good opportunity to add something that could be useful there.

After thinking about this occasionally over the past 3 months, I'd actually prefer not to add a separate new table transition type, even though I do think there is benefit in terms of simplifying certain areas. A few reasons:
1) It adds no new power or capability compared to the current complex transition.
2) It would require a lot of UI work when we don't have a lot of UI developer time available
3) Not all logic types map cleanly to this concept -- how would the "And", "Or", "At Least", etc condition types work? So it would need some concept of including/excluding logic types, possibly both in the UI and engine
4) It splits the logic into 2 places -- the "type" sits at the header of the table but different fields but there's an implicit or explicit "operator" and "comparison value" in the rows. It doesn't align super well with the current implementation of logical conditions. We'd have to either rewrite how logic works or duplicate or wrap every condition type just for this one transition.

I think adding lookup tables can cover everything you want to do with the table transition, plus adds additional capability that we could use elsewhere, so I'd push strongly to make lookup tables happen instead. It would still require UI work, but I suspect it would be simpler because the lookup table could just be a "dumb" plaintext-only grid.

**Comment by jawalonoski** [comment]
1. It isn't about adding, it is about simplifying.
2. We're going to have this problem with every GMF change moving forward.
3. It isn't meant to.
4. True, it uses implicit operators. If a value is given, then equality. If a range is given, then within the range. It doesn't need to align with logical conditions.

Remember, this is about lowering the bar for those with a background in public health, epidemiology, and health research -- where many data sets and published results are reported in tables.

I'd argue this is a similar change to the one we made with Diagnostic Reports.

It isn't about adding power or making the most elegant software design, it is about catering to our target user groups.

**Comment by dehall** [comment]
@jeffeastman Do you see this approach being extensible beyond just Gender, Age, and Race? Those 3 probably do cover the majority of use cases, but being able to plug in additional risk factors like smoking status could be useful in certain cases.

**Comment by jeffeastman** [comment]
I've implemented these tables with 3 classes: AgeLikelihoodRow, AgeLikelihoodTable & GenderAgeLikelihoodTable (GALT). You can see from the above that the gender table uses two age tables to achieve a third dimension of specification. I can imagine adding another class, maybe AttributeGenderAgeLikelihoodTable to allow a fourth dimension, but I've found that Conditional and Complex transitions using attributes are clearer. An example: in my Diabetes modules I use separate GALTs for each BMI range and use ConditionalTransitions to sample based upon the patient's BMI vital.

I've requested permission to release these classes and expect approval from MiHIN. Once this occurs I'll create a branch and make the other Synthea changes to integrate them into Logic.

**Comment by jawalonoski** [comment]
This issue has been addressed with #528 -- thank you @RobertScalfani
