### ISSUE TITLE
Editing Module

### ISSUE THREAD

**Issue by ShreyaPrasad31** [synthetichealth/synthea#314]
How can we edit the module so that the edited result reflects in the csv file. 
Eg. I want to add a precision medicine track in the Cancer Module, is editing the module using module builder enough if I want to see the result of the precision medicine track on the simulated patients.

Thanks!

**Comment by ShreyaPrasad31** [comment]
Yes I've loaded the json file in the modules folder. But calling run_synthea does not give the expected output.

**Comment by jawalonoski** [comment]
Well, you can try posting your module here or in the module-builder project, and maybe someone will be able to help you debug it. But there is currently not enough information available to help you.

**Comment by ShreyaPrasad31** [comment]
Thanks! I am attaching the module picture as well as the json file 
![for_mail](https://user-images.githubusercontent.com/23113117/40843352-b3b490ca-657e-11e8-96b4-dd0529a9949d.png)

Since github does not support the json format currently, I'm attaching a link to the google docs file 
https://docs.google.com/document/d/1O91K37TYhQY90Wf-XQxNfZlIo23iom7W4DMWvYHJxjY/edit?usp=sharing

**Comment by jawalonoski** [comment]
OK, thanks. I looked at your graph, but haven't tried to run the module [yet]. You said the module "does not give the expected output."

What are you expecting to happen? And then what is actually happening?

**Comment by ShreyaPrasad31** [comment]
I am trying to change the module so that the treatment for lung cancer follows the precision medicine route. 

In the graph after End_Diagnosis_Encounter IV the graph has been divided into NSCLC conventional and NSCLS precision medicine. Ideally I would want the csv -> patients file to have 4 more columns, with Mutation, Molecular Profile , Treatment and Response. 
Right now this is what the patients.csv file looks like https://docs.google.com/spreadsheets/d/1gNiHlQ74IjA0hZf3_CSoFI6ug0U0ik2pej88efhlRSk/edit?usp=sharing

Do you think I should delete the NSCLC Convetional Route after End_Diagnosis_Encounter IV altogether ?

**Comment by jawalonoski** [comment]
Thank you for the explanation. I have not yet reviewed the files, but a few things come to mind.

Immediately, the CSV output format -- for example adding new columns -- won't change without changing some of the Java code. However, you could get additional data in the `observations.csv` file if you add the specified precision medicine data to the patient record.

However, there are currently two reasons that data won't get added to the patient record: 

First, all of those states are `Simple` states, which don't actually do anything. See https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-States#simple for an explanation. You may want to try to change the type of these states to `Observation` and enter in some relevant mutation information as the values of those observations (rather than as the state name, which is what seems to be happening right now).

Second, it doesn't look like you set the value of the `Treatment Type` attribute anywhere. After the fourth encounter you are switching the path based on that value, but you don't actually set the value anywhere that I saw... so the behavior at that point is undefined.

**Comment by ShreyaPrasad31** [comment]
Pefect! I changed all the simple values to Observation, MedicationOrder etc
Can you direct me to the Java file which when modified would help get those values in the CSV file

**Comment by jawalonoski** [comment]
See https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/export/CSVExporter.java
