### ISSUE TITLE
How does the java code interact with the disease modules ?

### ISSUE THREAD

**Issue by ShreyaPrasad31** [synthetichealth/synthea#331]

**Comment by jawalonoski** [comment]
This is a complicated question. We probably could write an entire Wiki entry on it.

To start, the wiki contains fairly detailed documentation on the disease modules: https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework

This series of wiki pages may or may not answer your questions.

Beyond that, the java code is the engine that executes the disease modules. So, when a module starts an encounter or diagnoses a condition, or prescribes a medication -- the engine adds that to the record. When a module starts an encounter, the java code finds the provider organization. The java code determines (annually) the type of insurance a patient has. The java code is responsible for setting most (but not all) Vital Signs. The java code is responsible for aging and growth.

Is this the type of information you're asking for? Do you have specific questions?

**Comment by ShreyaPrasad31** [comment]
It does very well explain the high level functioning. To be specific about my question, suppose I am trying to add new columns to showcase precision medicine to the patients.csv file in synthea/output.
I would need to create a new module and store it in src/main/resources/modules/
I would then need to change the CSV.exporters file in src/main/java/org/mitre/synthea/export/

If we take the example of VitalSign.java. It has its own biometrics.yml file for weights/probabilities and assigning random numbers. 
I am assuming I will have to write my own java file called precision_medicine.java
This file should interact with the new module that will be created using the synthea module builder. How will it do that ?

**Comment by jawalonoski** [comment]
> I would need to create a new module and store it in src/main/resources/modules/
I would then need to change the CSV.exporters file in src/main/java/org/mitre/synthea/export/

Yes, you would need to create a new module. You only need to change the CSV exporter if you _insist_ that the output is recorded in `patients.csv` rather than `observations.csv`.

> I am assuming I will have to write my own java file called precision_medicine.java

Not necessarily. It is possible to add [Observation](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-States#observation) states or [SetAttribute](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-States#setattribute) states directly in the generic module to record genetic data.

`Observation` states are automatically recorded in `observations.csv`, but `SetAttribute` states do not. If you go that route, you'll have to modify the CSV exporter.

**Comment by jawalonoski** [comment]
I thought of this later... if you just use `SetAttribute` in your modules, you may be able to write a custom SQL report so that you don't need to modify an exporter at all.

See this recent pull request: https://github.com/synthetichealth/synthea/pull/325

(The Wiki page is pending...)

But the idea is that you write a SQL query in `src/main/resources/custom_queries.sql`. For example (I did not test this, but here is the idea):

```sql
select person_id, name, value from attribute where name in ('your_attribute1', 'your_attribute2')
```
