### ISSUE TITLE
Diabetes module

### ISSUE THREAD

**Issue by rukmal** [synthetichealth/synthea#336]
Hello, I noticed that there was a mention of Diabetes Mellitus Type 2 listed in the "Currently supported diseases" section on your [Wiki](https://github.com/synthetichealth/synthea/wiki), but I can't find the `diabetes.json` file in the `modules/` folder.

Can someone point me in the right direction? Thanks!

**Comment by jawalonoski** [comment]
Diabetes is contained in two files:

`metabolic_syndrome_disease.json`
`metabolic_syndrome_care.json`

Alternatively, you can view them in the module builder web app:

https://synthetichealth.github.io/module-builder/#metabolic_syndrome_care
https://synthetichealth.github.io/module-builder/#metabolic_syndrome_disease

**Comment by jawalonoski** [comment]
I closed the issue, but feel free to ask additional questions here or open another issue if you have problems. Thanks!

**Comment by rukmal** [comment]
Thank you Jason, I really appreciate it!

Quick question regarding the source for the guidelines; did your group model the workflow in the diabetes module using existing clinical practice guidelines (eg: [Standards of Medical Care in Diabetes](https://professional.diabetes.org/content-page/standards-medical-care-diabetes))?

**Comment by jawalonoski** [comment]
The models were based partially off of the 2016 edition of the [AACE/ACE Comprehensive Type 2 Diabetes Management Algorithm](https://www.aace.com/publications/algorithm)

**Comment by senadeniz** [comment]
Hi @jawalonoski ,
I experience some difficulties with running the metabolic_syndrome_disease and metabolic_syndrome_care. I couldn't figure out the module dependancies. I want to generate a dataset which includes age, state patient name or patient id, gender and diabetes patients. I would appreciate it if you could help.
Thanks,
Sena

**Comment by jawalonoski** [comment]
You should just be able to run Synthea as normal (or filtered to only those two modules if you prefer no comorbidities), and then filter out the patients who don't have diabetes.

So, generating a hundred patients looks like this:
```
./run_synthea -p 100
```

Generating a hundred with only the metabolic modules looks like this:
```
./run_synthea -p 100 -m metabolic*
```

By default, Synthea outputs the FHIR format. If you want to use FHIR, you can identify the patients with diabetes because their `./output/fhir/*.json` file will contain the text `Diabetes`.

If you want the CSV file, follow the directions at the [CSV Data Dictionary](https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary) page to enable Synthea to output CSV files. Then, you can identify the patients with diabetes by opening the `conditions.csv` file and filtering the rows that have a `description` field that contain the text `Diabetes`. You can obtain the patient demographics (e.g. gender, age) by joining the `patient` field in the `conditions.csv` file with the `id` field in the `patients.csv` file.

There are a number of ways that you can do that data processing, SQL might be easiest if you have a database, otherwise there are other methods and tools you could use that I leave to you.

Hope that helps.

**Comment by senadeniz** [comment]
Hi @jawalonoski ,
Thank you very much for your help. After running the metabolic modules, we couldn't obtain any patients with diabetes diagnosis. 
Is there any chance that the module has dependencies with other modules? 

And also is there any possibility to calculate diabetes prevalence rate from Synthea per state? Because when we looked into the "prevalence_template.csv" we couldn't see any information about state diabetes prevalence rates.
Thanks,
Sena

**Comment by jawalonoski** [comment]
@senadeniz,

I ran the exact command above:
```
./run_synthea -p 100 -m metabolic*
```

And got 8 patients with diabetes... which is about an 8% prevalence rate. If you run it, you might not get the exact same results due to random probability. You should see more diabetics as you scale up the population to 1K or 10K.

Here are the results of examining the `./output/csv/conditions.csv` file for that run:

Disease | Count
-- | --
Body mass index 30+ - obesity (finding) | 34
Anemia (disorder) | 32
Prediabetes | 29
Metabolic syndrome X (disorder) | 8
Hypertriglyceridemia (disorder) | 8
Diabetes | 8
History of cardiac arrest (situation) | 4
Coronary Heart Disease | 4
Cardiac Arrest | 4
Stroke | 3
Chronic kidney disease stage 1 (disorder) | 3
Hyperglycemia (disorder) | 3
Diabetic renal disease (disorder) | 3
Body mass index 40+ - severely obese (finding) | 2
Neuropathy due to type 2 diabetes mellitus (disorder) | 2
Diabetic retinopathy associated with type II diabetes mellitus (disorder) | 1
Atrial Fibrillation | 1

If you want to make use of the `prevalence_template.csv`, you need to alter the `synthea.properties` file:
```
exporter.prevalence_report = true
```
The prevalence template is not a well-document feature. Synthea will fill out the template when it runs, but since it can only run for a single state at a time, it cannot break out numbers by state. You'll have to manually do that manually by running Synthea for the states you're interested in. Even so, don't expect to see a wide variation across states -- Synthea doesn't currently replicate the "diabetes belt" for example.

**Comment by senadeniz** [comment]
@jawalonoski 
Thanks for your help it is very much appreciated! However I keep receiving the same error as in the below jpeg file even though I changed the synthea settings. Moreover, when I run .\run_synthea -p100 -m metabolic*, the program directs me to the help screen instead of filtering the modules.

Thanks,
Sena
![metabolic](https://user-images.githubusercontent.com/53124444/62559732-66629f80-b873-11e9-9b95-b215268d41a6.JPG)

![prevalence_settings_2](https://user-images.githubusercontent.com/53124444/62559500-0966e980-b873-11e9-99c4-dabc87164511.JPG)
![prevalence_synthea](https://user-images.githubusercontent.com/53124444/62559501-0966e980-b873-11e9-8ddd-7edaa60ef19d.JPG)

**Comment by jawalonoski** [comment]
There are two things going on here...

# 1. Database Does Not Exist
The error message says:
```
Unable to generate Prevalence Report - No database exists to generate report from.
```
You set `exporter.prevalence_report = true`, but you also need to set `generate.database_type = in-memory` or `generate.database_type = file`

The instructions are in the `synthea.properties` file screenshot you posted:
```
# note: prevalence and custom reports require a database (set below)
```

# 2. RuntimeException
The error message (unrelated to #1) says:
```
java.lang.RuntimeException: Unable to select a random city id.
```
I can't see if there are any errors above that, but that suggests to me that you have an issue with your demographics file, which defaults in `src/main/resources/geography/demographics.csv` and is set in the properties.
```
generate.demographics.default_file = geography/demographics.csv
```
Have you made any changes to that file? If yes, try to fix your file so it complies with the [Demographics File Format](https://github.com/synthetichealth/synthea/wiki/Demographics-for-Other-Areas#demographics-file-format). If no, try to update Synthea from `master`.

--- 

I'm going to lock this thread, because your issues are unrelated to the original issue. If you continue to have problems, please open a new issue thread and I'll try to help.
