### ISSUE TITLE
Multiple Value Sets

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#347]
Request from `#fhirdevdays` to allow a [ValueSet](http://hl7.org/fhir/STU3/valueset.html) to be specified (by canonical URL) instead of a code/coding in a module, so that things like Observations, Conditions, and Procedures can have varied codes.

**Comment by dehall** [comment]
Any recommended value sets that we can use? The FHIR / HL7 ones are very generic and grouped by category so probably aren't useful for our needs. (ex, there's one for "all SNOMED conditions" but not one for "all types of diabetes") VSAC has good ones but those require registration so we can't include them in the modules by default (unless we want people to have to register to use synthea).

**Comment by jawalonoski** [comment]
Step 1 is to create a FHIR `ValueSet` that defines a few diabetes codes. SNOMED, ICD9, etc. Put it in the resources. Reference that valueset by canonical URL in the `ConditionOnset` state. Randomly pick one code from the value set at diagnosis time.

Step 2. Reference a VSAC value set by canonical URL. It isn't found in the resources, but the properties file defines VSAC credentials. Use the credentials to pull the value set and proceed as above.

**Comment by dehall** [comment]
If we are going to use VSAC then I'd propose requiring a default code that it could fall back to if the user isn't online or doesn't have VSAC credentials.
But then it's also important to consider how this will work with `Active Condition` / `Active Medication` logic, and how this will work with claims pricing and disease burden evaluation. Not showstoppers by any means, just important to get right.

**Comment by jawalonoski** [comment]
I agree that a default code is required.

**Comment by rhdolin** [comment]
Greetings. I'm new to Synthea, and am just wondering if there is any more information on capabilities of using value sets when generating populations? Thanks.

**Comment by jawalonoski** [comment]
It is a capability that we have experimented with, especially using VSAC (account required), but have not merged into the master branch. Meaning it isn't part of the software today. We may return to this at some point, but it hasn't been a top priority for us.

**Comment by lawley** [comment]
Note, for SNOMED-based ValueSets you can make good use of the implicit ValueSet idea and avoid the need to explicitly create ValueSets.
For example, http://snomed.info/sct?fhir_vs=isa/12345678 is, __by definition__ the ValueSet for the code 12345678 and all its descendants.

You can also use SNOMED's ECL for more expressive definitions: this is all descendants of 12345678 that have a relationship 11111111 to 87654321 or any descendant
http://snomed.info/sct?fhir_vs=ecl/<<12345678:11111111=<<87654321

You could, for example, use this approach to match on specific morphologies or finding sites.

**Comment by jawalonoski** [comment]
@lawley That is a pretty good idea. How would we expand that "isa" or "ecl" at export time? Presumably we'd need a terminology service or the user would be responsible for a local cache of codes (with the hierarchy).

**Comment by lawley** [comment]
Yes, you'd want a terminology server for that.

https://r4.ontoserver.csiro.au/fhir/ValueSet/$expand?url=http:%2F%2Fsnomed.info%2Fsct%3Ffhir_vs%3Decl%2F+%3C+19829001+:+116676008+%3D+79654002

**Comment by rorydavidson** [comment]
Just to add to this thread, completely agree with @lawley, this should be via calls to a terminology server of which there are a few now available. 

The team here at SNOMED International are investigating if we can develop and contribute code to Synthea enabling the ability to call out to any FHIR Terminology Services compliant terminology server in order to use ECL and other direct SNOMED CT queries.

Hopefully, we can update this soon!

**Comment by rdingwell** [comment]
Keep in mind that you need to be careful with any approach that just selects a random code from a valueset.  Codes in valuesets can be tied to other aspects of the patient where selecting a random code can create conflicting/unrealistic information in the record. 

Take diabetes for instance.  Diabetes can be caused by pregnancy, medications, alcoholism ... If you have a valueset that represents all Diabetes and then select a code at random there is the real possibility that you would give a male generated patient a pregnancy induced diabetes code.  

This is the approach we took when we first generated patients for quality measures based on the measures and the valuesets that they contained.   Synthea is much more advanced than what we were doing but valueset code selection would still be an issue without understanding what the code being selected means and how that current patient context influences the code selected or how the code selected should influence the future code generation.

**Comment by jawalonoski** [comment]
Closed with #709.   

In order for ValueSets to be used, you need to specify a FHIR terminology server using the `generate.terminology_service_url` property and have a module with ValueSet specified.

ValueSets can be specified in any [State](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-States) that contains a `code`. Just add a `value_set` attribute in addition to the system, code, and display.

For example:
```json
{
  "system": "SNOMED-CT",
  "code": "2501000087107",
  "display": "MRI of right knee with contrast",
  "value_set": "http://snomed.info/sct?fhir_vs=ecl/<<2491000087104"
}
```

**Comment by gjajk1** [comment]
Is it possible to use a value set that is specified using a file based URL?  I was hoping to try something like: 
        {
          "system": "SomeSystem",
          "code": "555555",
          "display": "Examplitis",
		  "value_set":"\\\?\\C:\\Synthea_Basic\\valueSets\\ICD10otitis.json"			  
        }
I tried variations on the URL syntax for file locations.  They all seem to be ignored. Synthea runs to completion and I see the "SomeSystem" and code 555555 in the output. But what I am trying to do is have synthia go to the json file (which is in FHIR format) and pull a code from the file. It seems the value set path is ignored. 

I don't have a FHIR server available but was hoping Sythea could resolve file paths to value_set files.

Any insights would be appreciated.    Regards, George

**Comment by jawalonoski** [comment]
Is it possible today? No, it just doesn't work like that.

Could it possibly work that way in the future? Maybe. But it would require some special logic.

Typically, a `value_set` is not a URL for the file or web location (although it could be), it is typically the canonical URI for the ValueSet. For more information see the explanation for `ValueSet.url` under the ValueSet Identification Heading: http://hl7.org/fhir/R4/valueset.html#ident
