### ISSUE TITLE
Encounters, vitals, panels... way after death

### ISSUE THREAD

**Issue by cmoesel** [synthetichealth/synthea#409]
I don't know if this happens a lot or if I just got lucky -- but I was looking at a patient and noticed her deceasedDateTime was `"1992-08-05T00:53:26-04:00"`, but she had several encounter, observations, and panels from 1993.  The file is attached (w/ txt extension so GitHub allows it).

[Jodie811_Leffler128_0de37a5a-b57c-4871-afc8-c819f8567cbc.json.txt](https://github.com/synthetichealth/synthea/files/2311986/Jodie811_Leffler128_0de37a5a-b57c-4871-afc8-c819f8567cbc.json.txt)

This was generated from current `master` branch.

**Comment by KeeyanGhoreshi** [comment]
In the docs for the death state this behavior is explained.

`Implementation Warning: If a Death state is processed after a Delay, it may cause
inconsistencies in the record. This is because the Delay implementation must rewind time to
correctly honor the requested delay duration. If it rewinds time, and then the patient dies at
 the rewinded time, then any modules that were processed before the generic module may have
created events and records with a timestamp after the patient's death.`

**Comment by dehall** [comment]
Very strange. The death certification has a date of 1993-09-01 and cause of death is "natural causes". I haven't seen this before but I'll keep an eye out. @KeeyanGhoreshi is right that the rewinding time can cause some weirdness, but it should only be within a single timestep -- 7 days by default

**Comment by anujm03** [comment]
This problem still exists and in some cases the encounter occurs years after death. See attached.
[post_death_encounters.xlsx](https://github.com/synthetichealth/synthea/files/3408477/post_death_encounters.xlsx)
