### ISSUE TITLE
ExplanationOfBenefit.provider being set to an Organization

### ISSUE THREAD

**Issue by CarthageKing** [synthetichealth/synthea#440]
ExplanationOfBenefit.provider only accepts a Practitioner type reference: http://hl7.org/fhir/STU3/explanationofbenefit-definitions.html#ExplanationOfBenefit.provider

However the following code in FhirStu3.explanationOfBenefit() sets it to an Organization.
```
    Provider provider = person.getProvider(encounter.type, encounterResource
        .getPeriod()
        .getEnd()
        .getTime());
    if (!inpatient && !outpatient) {
      eob.setProvider(new Reference().setReference(findProviderUrl(provider, bundle)));
    } else {
      eob.setProviderTarget(new Practitioner()
          .addIdentifier(new Identifier()
              .setValue("yes")));
    }
```

Either this should be set to use .setOrganization() instead or to find the Clinician instead then set that to .setProvider()

**Comment by fil512** [comment]
Experiencing same issue here.  Suggested workaround?

**Comment by jawalonoski** [comment]
Yeah... I put in a _technical_ fix for this just now, but it isn't ideal. The Blue Button 2.0 Implementation Guide **requires** some weird references (using an Identifier rather than a reference URL), so the resource will now validate to the correct resource types... but they'll be Identifiers instead.

**Comment by fil512** [comment]
Thanks!!
