### ISSUE TITLE
Codecov complaining on files I haven't touched

### ISSUE THREAD

**Issue by adamdavis40208** [synthetichealth/synthea#456]
For example:

https://github.com/synthetichealth/synthea/pull/451

I touched a couple files and added tests for anything I touched, but the Codecov output complains about quite a few export files.

Is something misconfigured in codecov?

**Comment by adamdavis40208** [comment]
That style of testing is great

**Comment by tiloc** [comment]
@dehall I totally get the point of randomized testing. However, I recently had a hard-time submitting a PR since I got varying results in the automated build checks. I wasn't sure whether I had broken something (it worked on my machine) or whether this was due to a bug in the FHIR export. I think there should be a consistent run for unit tests, and the option to start a long-running random test to unearth rare bugs (kind of a "fuzzing" approach).
Just my $0.02.
