### ISSUE TITLE
Column Name Clarification for CSV Export

### ISSUE THREAD

**Issue by fdefalco** [synthetichealth/synthea#481]
The Wiki has column names with spaces in them for the imaging studies table.  

https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary#imaging-studies

The CSV exporter linked below creates column names with underscores.  Other tables seem to use camel case.  Are the underscores inferred from the spaces in the data dictionary?

https://github.com/synthetichealth/synthea/blob/6dbf88c6ab83425fb5964c99f04a8d6a1a921ecf/src/main/java/org/mitre/synthea/export/CSVExporter.java#L195

This seems generally inconsistent from tables like Encounters with column names like ReasonCode, for example.  Just looking for guidance on how we should script our DDL as we import the CSV output.

Thanks!

**Comment by jawalonoski** [comment]
You are correct, the underscores are inconsistent. The other tables use ALLCAPS and NOSPACES in the column headers, with the exception of `Id` columns due to the [SYLK issue](https://github.com/synthetichealth/synthea/issues/443). I'm happy to have the underscores removed for consistency purposes.

We also used "human readable" names in the wiki data dictionary, for the sake of, well, human readability. We can change the wiki match the column headers exactly if you think it would be worthwhile.
