### ISSUE TITLE
Find anomalies in the prescribed medication or suggested care plans or procedures 

### ISSUE THREAD

**Issue by shawrk3387** [synthetichealth/synthea#504]
Hi, I am planning to develop an anomaly detection system on Synthea dataset. The goal is to find any anomaly in either of the following-
1. Medication
2. Care plan
3. Procedure
But I am facing challenges while merging all the CSVs into one. Any kind of help in merging all the CSVs will be highly appreciated.

**Comment by jawalonoski** [comment]
Well, the CSV files are relationally linked, so merging them into one giant table is possible, but weird. The biggest issue will be how you choose to handle time.

Please see the [CSV File Data Dictionary](https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary), if you haven't already.

Here is the overview:

- The central table is Patient.
- Each patient has multiple Encounters, each with a different date.
- The other tables are linked to Encounter. In other words, an encounter has (or contains) a variable number of conditions, procedures, medications, and so forth.

If you want "_one CSV file to rule them all_", you'll have to think about how you handle time... each time is a separate row, or each time is a separate column (in which case, you'll have a variable number of columns).

Hope that helps.

**Comment by shawrk3387** [comment]
Thanks Jason. But I still have the confusion. Could you please explain how can I join just the Careplan and Medication csv?

**Comment by jawalonoski** [comment]
Well, it is up to you to use whatever tools or techniques you want to join them.

That being said, the [careplans](https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary#careplans) file has links to [encounters](https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary#encounters):
```
careplans.encounter == encounters.id
```

Similarly, the [medications](https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary#medications) file has links to [encounters](https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary#encounters):
```
medications.encounter == encounter.id
```

So, if you want to join the `careplans` and `medications` tables together you join them on `encounter`
```
careplans.encounters == medications.encounters
```

Of course, joining `careplans` and `medications` might not make any sense, because each `encounter` might have many things occurring that are unrelated. For example, in an encounter a doctor prescribes a patient medication for an ear infection, and also gives them a care plan to stop smoking and diet. Those things have nothing to do with each other.
