### ISSUE TITLE
Opioid addiction module

### ISSUE THREAD

**Issue by shawrk3387** [synthetichealth/synthea#511]
Hi, I was trying to download data related to opioid addiction using the following command. Unfortunately nothing gets downloaded, may be I am doing something wrong. Kindly assist. Thanks!

.\run_synthea.bat -m opioid_addiction --exporter.csv.export true

**Comment by jawalonoski** [comment]
Synthea does not download data, it generates data. Your command also functions correctly on my system.

You could try generating more patients with the `-p` flag:
```
./run_synthea -p 100 -m opioid_addiction --exporter.csv.export true
```

Either way, not all patients will be opioid addicts, just because you specified that module. It works based on probability (e.g. some percentage of people will take opioids and get addicted), not forced assignment (e.g. make everyone an opioid addict).

Finally, filtering out modules using the `-m` flag will not eliminate the build-in modules (e.g. immunizations, growth, cardiovascular disease).
