### ISSUE TITLE
Newbie Question:  Module edits not reflected in output folder

### ISSUE THREAD

**Issue by awatson1978** [synthetichealth/synthea#576]
Hello!
So, we've cloned a copy of the `synthea` project to our local workstation, have been hacking on `modules/congestive_heart_failure.json` and making some simple edits like replacing the Ultrasound procedures with Magnetic Resonance procedures and not adjusting anything else in the module.

But when I run the script with `./run_synthea -s 12345 -m heart* -p 100 California "Los Angeles"` none of the output files have the MRI exams in them.

Do we need to recompile synthea to use the custom congestive_heart_failure file? Is there a command line option that we specify for the .json file?  

I'm pouring through the documentation, but not finding anything on recompiling the software; and our edits don't seem to be reflected in the output.

**Comment by chrissten** [comment]
Yes. If you compile it according to the instructions, all the modules are stored in the synthea.jar and editing them outside will have no effect. so yes, you need to recompile after making edits to your modules. What I did was clone, compile, and then remove the reference to synthea.jar and run from Eclipse. This makes it much easier rather than running gradle every time.

**Comment by awatson1978** [comment]
Ah!  I got it to work.  Just needed to run `./gradlew build check test` again.  That was way less painful than I feared.  Thank you so much!
