### ISSUE TITLE
Adding new resource

### ISSUE THREAD

**Issue by Asinha2810** [synthetichealth/synthea#622]
Hi 
i need to add new resourceType in the output file which we get after running Synthea..
Can you please help me out with the code where we can make changes ????

**Comment by jawalonoski** [comment]
All of the export code exists in the `org.mitre.synthea.export.*` package. Find the java file that corresponds with the format you want to alter, and dive in.

Since you said "resourceType" presumably you are talking about FHIR. The current default version for FHIR in Synthea is R4. That exporter is here: 

https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/export/FhirR4.java

The exporters need to write out data from the `HealthRecord` class. The API for that class is here: https://synthetichealth.github.io/synthea/build/javadoc/org/mitre/synthea/world/concepts/HealthRecord.html

Other data, can be found on the `Person`: https://synthetichealth.github.io/synthea/build/javadoc/org/mitre/synthea/world/agents/Person.html

**Comment by Asinha2810** [comment]
Hi 
After reading the documentation of Synthea i just got to know how to run and generate the patient details randomly but cant find the files that it is using to generate the data or the code from where it is taking the data and generate the given data

The usecase of my project is:

1.  I need to generate patient data that is customizable and not randomly generated.
2. let us suppose for the resourcetype Patient i need to generate data that has the address parameter that would by set by me.

i cannot find the file where i can define my custom data and do the connectivity so that the customized data would be created 

The timeline of my project is less so can you please show me the path so that i can do the required changes.,

would appreciate your time on this..
Thanks in advance..

regards,
animesh

**Comment by jawalonoski** [comment]
Synthea does not generate synthetic data based on some other preexisting dataset.

The way to customize the data, is by either (1) modifying an exporter, (2) modifying the demographics and locations, or (3) modifying the disease models that determine the clinical content.

I already discussed (1) in my previous comment, so I'll skip that.

For (2), if you want other demographic information or addresses, you need to follow these instructions: https://github.com/synthetichealth/synthea/wiki/Other-Areas

For (3), if you want other clinical data, you need to modify the disease modules. You can do that by following the wiki tree starting with https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework and using the [Module Builder](https://synthetichealth.github.io/module-builder/).

**Comment by Asinha2810** [comment]
Hi
Thanks for the review on the above issue.
one more scenario was that if need to get the records on the basis of specific disease like  i need to get 10 records of patient having the same disease **asthma**, where i need to make changes in the code ??

**Comment by jawalonoski** [comment]
Either you follow the directions for (3) above, and modify the module so that asthma is much more prevalent... or you generate lots of extra patients (using the `-p` flag on the command line) and then filter down to patient records with asthma.
