### ISSUE TITLE
Symptoms are not found in FHIR output

### ISSUE THREAD

**Issue by alexissmirnov** [synthetichealth/synthea#638]
running `./run_synthea -m sore_throat -p 10` produces a patients with the condition defined in that module (eg. "Acute viral pharyngitis (disorder)" or "Streptococcal sore throat (disorder)"). Those appear in the output FHIR JSON documents.

But symptoms defined in the sore_throat module are not found in the output.

Why would the symptoms defined by the module are not included in the output?

**Comment by jawalonoski** [comment]
As described in the wiki, [Symptoms](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-States#symptom) are used to drive patient behavior. As symptoms accumulate (across all modules), it will cause them to schedule an encounter (outpatient, urgent care, or emergency) depending on the number and severity.

`Symptom` states are not meant to appear in the record, which is why they are uncoded. If you want something to appear in the record, they should be `ConditionOnset` or `Observation` states.

We have considered adding the text description of the symptom into clinical notes that are generated, so they documented (but not encoded with something like a SNOMED code), but that does not current exist in the output.

**Comment by alexissmirnov** [comment]
Have you considered adding a new clinical state to the Generic Module Framework, being simply a SNOMED expression? Such a generic state would allow a much higher expressiveness for generic modules, and an export component would be able to select which SNOMED states it would output, and what format to use.

**Comment by jawalonoski** [comment]
You should be able to use [ConditionOnset](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-States#conditiononset) for that.

You should be able to write a SNOMED expression in the `code` field.
