### ISSUE TITLE
How to upload synthea generated data to FHIR Server 

### ISSUE THREAD

**Issue by usmanbahadur** [synthetichealth/synthea#652]
I have used Synthea patient generator to generate a list of patient which currently sits in .output/fhir file. what's the best way to POST to FHIR Server that uses token  based access OAuth 2.0, an example code would be very helpful. 

The document says that we can use the code below to upload patient to server. I have tried command below in terminal but i get the error. 

> curl http://hapi.fhir.org/baseR4/  --data-binary "C:/Users/Me/Documents/Synthea/synthea/output/fhir/Zarate81_0f2a699f-698a-47bd-b8fb-f1b80120c251" -
H "Content-Type: application/fhir+json

```
<!DOCTYPE html>
<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<title>Access Denied</title>
<style type="text/css">body {margin:0;font-family:verdana,sans-serif;} h1 {margin:0;padding:12px 25px;background-color:#343434;color:#ddd} p {margin:12px 25px;} strong {color:#E0042D;}</style>
</head>
<body>
<h1>Access Denied</h1>
<p>
<strong>You are attempting to access a forbidden site.</strong><br/><br/>
Consult your system administrator for details.
</p>
</body>
</html>curl: (6) Could not resolve host: application
```

**Comment by jawalonoski** [comment]
@usmanbahadur Thank you for using Synthea.

Unfortunately, providing step-by-step security instructions for your specific server (or OAuth2 in general) are out of scope here. You should ask for instructions from your vendor or the developers of your FHIR server.

Also, I assume you are not connecting to the HAPI endpoint actually listed in your post, because it is not secured.

All that being said, it is possible that your FHIR server is secured using the SMART-on-FHIR authorization scheme. If so, you should review the following resources, make sure you have registered security credentials, and actually have scopes/permissions to write data to the server.

- http://hl7.org/fhir/smart-app-launch/index.html
- https://hl7.org/fhir/uv/bulkdata/authorization/index.html

Finally, in general, if you are intent on using curl, you can find additional instructions by searching for _"oauth2 curl commands"_
