### ISSUE TITLE
How to generate cancer patient data?

### ISSUE THREAD

**Issue by jananiarunachalam** [synthetichealth/synthea#722]
Hello, I tried generating cancer patient data after commenting out "Cardiovascular disease" following this [issue](https://github.com/synthetichealth/synthea/issues/546#issue-469889073).

Command used: `./run_synthea -p 1000 -c <file path> -m *cancer`

I only got one entry in the "Conditions.csv" which had "cancer" in it. Am I doing something wrong?

Thank you for you help!

**Comment by jawalonoski** [comment]
> Am I doing something wrong?

Probably not, but it might depend on what is in your configuration file.

Synthea should tell you the modules it loaded using that filter. You should see something like:

```
Modules: Breast_cancer Module
       & Colorectal Cancer Module
       & Lung Cancer Module
       & Veteran Lung Cancer Module
       & Veteran Prostate Cancer Module
       > [5 loaded]
```

I ran the command you provided, opened the `conditions.csv` file with Excel and created a pivot table. The yellow highlighted rows below are related to cancer.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/1054765/83032451-d5c49e00-a003-11ea-9312-23c1de5d98d0.png">

The command you provided does **not** guarantee that patients will all have cancer, it only simulates their lives with the filtered set of modules. Given the demographics of the population (newborns to old age) the overall rate of cancer at the given moment is probably going to be low, even though the lifetime rates are higher.

**Comment by dehall** [comment]
I'm marking this issue closed because it appears to have been resolved, but feel free to re-open it if there are further questions.

Also a note for posterity - since this question was posted, we have added a new feature called the "keep patients module", where it is possible to define criteria that you want exported patients to meet. For example, one could create a keep module where patients with active breast or lung cancer go to a Keep state.
See more at: https://github.com/synthetichealth/synthea/wiki/Keep-Patients-Module
