### ISSUE TITLE
FHIR Export Duplication Data and Transactions

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#795]
See this thread: https://chat.fhir.org/#narrow/stream/179239-tooling/topic/Synthea/near/210288132

Summary of requested change:

- When transaction bundles, organization, and practitioner FHIR exports are enabled (or create a separate explicit configuration parameter):
    - Do not duplicate Organizations and Practitioners in each Patient bundle.
- Change transaction POSTs to be [conditional creates](https://www.hl7.org/fhir/http.html#ccreate) using the `ifNoneExist` parameter
- Add an option for conditional references (see https://www.hl7.org/fhir/http.html#trules)

**Comment by barabo** [comment]
I implemented a [data loader script](https://github.com/microsoft-healthcare-madison/patient-lists-demo/blob/master/data/bin/load.py) in python to modify a Synthea export to be loaded in this way and what I learned was:

- I needed to [add](https://github.com/microsoft-healthcare-madison/patient-lists-demo/blob/680feb2ac2897b1f762b5ac85a2df7a5bcc29564/data/bin/load.py#L77) the Synthea uuid `identifier` to most resources
- Certain resource types do not contain an `identifier` (like `Providence`), preventing conditional references to them (fortunately there was no need in this case).
- I needed to [post](https://github.com/microsoft-healthcare-madison/patient-lists-demo/blob/680feb2ac2897b1f762b5ac85a2df7a5bcc29564/data/bin/load.py#L248) each bundle entry to the server in a separate bundle to ensure that the server had created the resource before it was referenced.  I *could* have been smarter about bundling multiple entries with no dependencies together (saving on network throughput and overall server transactions), but it was performant enough to bundle one at a time.
- I needed to [create a partial ordering](https://github.com/microsoft-healthcare-madison/patient-lists-demo/blob/680feb2ac2897b1f762b5ac85a2df7a5bcc29564/data/bin/load.py#L141) of the patient resources to ensure that I posted resources before they were first referenced.
It would be helpful if Synthea could order the resources in the patient bundle in such a way that all referenced resources were listed before their first reference.

**Comment by hadleynet** [comment]
Here is an approach I think could work:

- Output the `Organization`, `Location` and `Practitioner` in separate bundles using the `exporter.hospital.fhir.export` and `exporter.practitioner.fhir.export` options. We will modify the exporter so that these are output as `batch` bundles with `ifNoneExist` preconditions. We will also modify the `Location` export so that the `managingOrganization` reference uses the `Organization` identifier to allow it to import without reference errors.
- We will modify the per-patient `transaction` bundle exporter so that, when the `exporter.hospital.fhir.export` and `exporter.practitioner.fhir.export` options are specified, `Organization`, `Location` and `Practitioner` resources will be omitted. We will utilize [search URI references](https://www.hl7.org/fhir/http.html#trules) in any resource in the patient bundle that needs to refer to an `Organization`, `Location` or `Practitioner`.

You would first load the hospital and practitioner bundles, then each of the patient bundles. The only reference that wouldn't be fully resolved would be the `Location.managingOrganization`. There should be no duplicate `Organization`, `Location` or `Practitioner` resources once the load is completed.
