### ISSUE TITLE
Diabetes and COVID19: error with -m metabolic*

### ISSUE THREAD

**Issue by Joeyccc** [synthetichealth/synthea#866]
Hi, I want to look for a relationship between diabetes and COVID19. 

I started with 
`run_synthea -p 5000 -m metabolic* --exporter.csv.export true`

and go the following error: 
`java.lang.NullPointerException at App.main(App.java:106)`
![image](https://user-images.githubusercontent.com/33188234/110526678-0b7ce280-8151-11eb-95c3-3b416f53ae2c.png)

If I do `>run_synthea -p 5000 -m metabolic_syndrome_disease --exporter.csv.export true`, it runs ok, but there is no patients with diabetes in conditions.csv.

Your help is greatly appreciated.

**Comment by dehall** [comment]
@Joeyccc the short answer is you probably don't want the `-m` flag at all. Try just `run_synthea -p 5000 --exporter.csv.export true` and you should see patients with diabetes and with COVID19.

To elaborate on that, by default synthea runs with all included modules, and the `-m` flag basically says "run with only these modules", keyword "only". 
The metabolic syndrome module also adds another layer of confusion here. Unlike most other modules, this one is split out into separate disease progression and treatment modules, so if you only load one without the other, it won't work as expected. 

One of our most-often requested features is the ability to "only generate patients with condition X" but unfortunately we don't have that feature yet. So we generally recommend generating a larger dataset then filtering down to the conditions of interest.

**Comment by dehall** [comment]
Upon closer inspection, you've uncovered a bug in our Windows batch script. So thank you for pointing that out.

The technical cause is, when it's iterating over the command line arguments, it's evaluating them when it shouldn't be. You probably don't have any files matching the pattern `metabolic*` in the folder you are calling run_synthea from, so that evaluates to nothing. And unfortunately there's no way to quote or escape character to prevent that. We need a code change, which I'll submit a PR for.

In the meantime, like I said I would recommend not using the -m flag anyway.

**Comment by Joeyccc** [comment]
@dehall Got it, thanks!
