### ISSUE TITLE
trouble while posting the generated modules(json) into HAPI 

### ISSUE THREAD

**Issue by vbchinnam** [synthetichealth/synthea#877]
I have generated modules for HIV and the generated patient records are in FHIR. 
next step is to post the files to HAPI. while posting ,  I used the following command 
# post the hospital bundle
cat hospital*.json | curl -X POST -H "Content-Type: application/fhir+json;charset=utf-8" --data-binary @- http://localhost:8080/fhir.

But it is throwing below error.(PFA)

Appreciate your  time and response

<img width="642" alt="post_error" src="https://user-images.githubusercontent.com/77992736/115941787-86cdf580-a46c-11eb-90ae-9fcf4ca9d88e.PNG">

**Comment by jawalonoski** [comment]
I just stood up a fresh instance of HAPI (latest) -- so the database was empty.

Using the latest Synthea code, the command you supplied completed without errors.

:warning: Your error is that you are trying to load more than a single hospital file at a time.

:warning: `hospital*.json` is resolving to more than one file, which will not work, because more than one file concatenated together is not valid JSON.
