### ISSUE TITLE
Overlapping encounters

### ISSUE THREAD

**Issue by dehall** [synthetichealth/synthea#883]
It's possible for two encounters on a patient's record to overlap. Seems like what's happening is a wellness encounter starts, then a disease module starts another encounter during the same timestep, then the subsequent modules that run are considered to be "in a wellness encounter" but when it calls getCurrentEncounter it gets that second one. 

In terms of timestamps everything that occurs within the 2 modules generally makes sense, but if you group by encounter ID you get weird things like a patient who is diagnosed with hypertension but they don't have a blood pressure reading. (because the bp reading happens in wellness_encounters.json and the diagnosis happens in hypertension.json)

**Comment by jawalonoski** [comment]
I hesitate to create a new issue, because it is not exactly the same problem, but it results from the same causes...

Some encounters are not properly closed, or are seemingly randomly closed _years after_ they are started when the GMF suggests the module should be closed within hours or days. I have found this occurs with submodules -- the Anemia submodule is a frequent culprit.

My suspicion is that this is because the "current encounter" can change or become `null` -- which may be related to modules creating overlapping encounters.

The context of a module (e.g., the module, the current provider, the current encounter, the prior history -- to include submodules) is in need of a reorganization. This is also vaguely related to #1003.

**Comment by jawalonoski** [comment]
This was fixed with #1245
