### ISSUE TITLE
issue with LOOKUP tables

### ISSUE THREAD

**Issue by vbchinnam** [synthetichealth/synthea#905]
Hello,
I have trouble with lookup tables.
I need patients to be generated by age and gender, so I choose table transition and gave all the values as per the example given.
I named the column headers according to the states. later, named the tables and downloaded the files and saved them in (main/resources/modules/lookup tables ).
after generating the data and analyzing, I found the data is not generated accordingly.(lookup table probabaility)
Is there anything else i missed to perform on lookup tables?
how much should be given as  the default probability?(I tried both 100% and 0%)(still not working).

here I am attaching my JSON of that lookup tables.
![image](https://user-images.githubusercontent.com/77992736/122842968-ff61fe80-d2c3-11eb-9875-1939591677aa.png)
this is how I hardcoded my data for lookup tables
age,gender, HIV_Positive, HIV_Test_Negative
0-4,F,0.02,0.98
5-9,F,0.11,0.89
10-14,F,0.08,0.92
15-19,F,0.12,0.88
20-24,F,0.34,0.66
25-29,F,0.6,0.4
30-34,F,0.95,0.05
35-39,F,0.87,0.13
40-44,F,0.119,0.881
45-49,F,0.106,0.894
50-54,F,0.117,0.883
55-59,F,0.09,0.91
60-64,F,0.62,0.48
0-4,M,0.06,0.94
5-9,M,0.05,0.95
10-14,M,0.13,0.87
15-19,M,0.05,0.95
20-24,M,0.06,0.94
please let me know if made any mistakes in the process or if i need to add any other step.(please let me know if any other details are missed to help out)
Appreciate your help.

Regards
Bhavana

**Comment by jawalonoski** [comment]
You shouldn't have both default probabilities be `1`... both numbers should sum to 1. So, you could make one `1` and the other `0`, for example.

Also, do not copy and paste out of the JSON window. **Use the Download button**.

The JSON, after you download it, should look something like this (this example is not complete):

```json
  "New_State": {
      "type": "Simple",
      "lookup_table_transition": [
        {
          "transition": "New_State_2",
          "default_probability": 0.8,
          "lookup_table_name": "file.csv"
        },
        {
          "transition": "New_State_3",
          "default_probability": 0.2,
          "lookup_table_name": "file.csv"
        }
      ]
    },
```

The JSON file should be in `src/main/resources/modules/your_module.json` (or whatever you name the JSON file) and the CSV table should be in `src/main/resources/modules/lookup_tables/file.csv`. Notice that the paths are different. The file name in the JSON needs to match the file name in the `lookup_tables` folder.

The results are not going to be exact, but they should be close, especially as you generate more and more patients. If you have probability of 0.96, do not expect exactly 96 out of each 100 to have the result in question. Generate _at least_ 10K patients to see the results at scale.

Also, use the covid-19 lookup tables as working examples.

**Comment by vbchinnam** [comment]
Appreciate your response and time 

I did followed the same way as you have mentioned and generated 10k patients but none of the patients are in the given age range as in the lookup table. when I give probability as 0.3 for positive condition and 0.7 for negative condition.
300/10k are generated positive and 700/10k are negative. 
however, the generated 700 &300 are not in the age ranges provided in the lookup tables.
please let me know how to deal with this


Thankyou
Appreciate your help.

**Comment by jawalonoski** [comment]
Try setting `exporter.years_of_history = 0`

**Comment by jawalonoski** [comment]
You might be filtering out old data.

**Comment by vbchinnam** [comment]
hi @jawalonoski 
Thankyou for taking time out to help me.
After changing the above setting also, lookup tables are not working. it is just generating the numbers based on the default probability, but not by age and gender (lookup table).
![image](https://user-images.githubusercontent.com/77992736/123683356-b8b75b80-d811-11eb-8ebb-bf4305c6cd97.png)
This is how I am giving my probabilities by age and sex into the module builder and then I kept the downloaded csv files in their destination.



Please help me with this.

**Comment by jawalonoski** [comment]
> Please help me with this.

The instructions I provided previously about where to place the JSON and CSV files should work (illustrated below), if you follow them carefully. Make sure the module references `hiv_data.csv` and **not** `lookup_tables/hiv_data.csv`.

```
/synthea
  /src
    /main
      /java
      /javascript
      /resources
        /costs
        /geography
        /modules
          hiv.json <--- put your module here
          /lookup_tables
            hiv_data.csv <---- put your table here
```
At this point, there isn't much more I can do, unless you point me to a GitHub repository.

**Comment by vbchinnam** [comment]
Hi @jawalonoski 
here I am attaching the git hub repository link for modules and lookup folder.
I have attached the complete module  folder. 
mod.json is the json file which is in module folder

https://github.com/vbchinnam/synthea
Please let me know if any other things are needed to help us.

Thankyou so much for being patient and help

Much appreciated.

**Comment by vbchinnam** [comment]
Hi @jawalonoski 
Following up to see if you got a chance to check my repository.
Appreciate your help.

**Comment by jawalonoski** [comment]
These modules function.

Steps I took:
```
cd git/
mkdir vbchinnam
cd vbchinnam/
git clone https://github.com/vbchinnam/synthea.git
cd ~/git/synthea
cp ~/git/vbchinnam/synthea/modules/final_hiv.json src/main/resources/modules/
cp ~/git/vbchinnam/synthea/modules/lookup_tables/*.csv src/main/resources/modules/lookup_tables/
rm -R output/
./run_synthea -p 1000 --exporter.csv.export=true --exporter.years_of_history=0
grep "75622-1" output/csv/observations.csv 
grep "45260-7" output/csv/observations.csv
grep "25836-8" output/csv/observations.csv
```

The lookup tables are being found and they are functioning without error.

Let's look at the data in `./output/csv/observations.csv`:


## Tests

Gender | Age | HIV Negative | HIV Positive
-- | -- | -- | --
F | 0 | 270 | 275
M | 0 | 328 | 312


## ART

Gender | Age | Count
---|---|---
F|0|275
M|0|312

## VLS

Gender | Age | Count | Min | Average | Max
-- | -- | -- | -- | -- | --
F | 0 | 275 | 10772.9 | 476470.4345 | 992186.8
M | 0 | 312 | 3458.7 | 518117.4574 | 999684.1


## Expected vs. Actual

So what is the problem?

Well, for one thing, everyone is aged 0 years. You probably didn't expect that.

Second, the distribution is closer to 50/50 than anything in your `hit_data.csv` table. Why?

Well, because everyone is a newborn baby. Your table does not have an entry for anyone under 15 years old, so the module reverts back to your default probabilities.... which are 50% for each outcome.

Why is everyone a newborn baby?

Because all patients in Synthea start as newborn babies. Your module doesn't have any `Delay` states, or `Guard` states, or even `Encounters`. So, the module executes _immediately_ as soon as the baby is born. Right inside the maternity ward the nurses are administering an HIV test.

Probably not what you wanted.

See [Age: Guard vs. Delay](https://github.com/synthetichealth/synthea/wiki/Age%3A-Guard-vs.-Delay) for an explanation.

## How do you fix this problem?

Use a `Delay`, or a `Guard`, or both. And what the heck, an `Encounter` as well. I tried this solution (you'll have to recreate this on your own):

![image](https://user-images.githubusercontent.com/1054765/124808192-a1bceb80-df2c-11eb-98bf-a5b3825104de.png)

## Final Results

I ran another 1000 patients.

337 tested negative, and 28 tested positive (see table below for breakdown).

What about the rest of the patients? The other 635 patients? Well, they weren't tested. That is because the `Delay` state I added above (randomly delays between 0 and 49 years) did not finish for all the patients.

Gender | Age | HIV Negative | HIV Positive | Total
-- | -- | -- | -- | --
F | 15 | 9 |   | 9
M | 15 | 13 |   | 13
F | 16 | 5 |   | 5
M | 16 | 12 |   | 12
F | 17 | 12 |   | 12
M | 17 | 6 |   | 6
F | 18 | 11 | 1 | 12
M | 18 | 7 |   | 7
F | 19 | 10 |   | 10
M | 19 | 9 |   | 9
F | 20 | 4 |   | 4
M | 20 | 4 |   | 4
F | 21 | 2 |   | 2
M | 21 | 3 |   | 3
F | 22 | 16 |   | 16
M | 22 | 18 | 2 | 20
F | 23 | 3 | 1 | 4
M | 23 | 3 |   | 3
F | 24 | 1 |   | 1
M | 24 | 4 |   | 4
F | 25 | 17 | 1 | 18
M | 25 | 11 | 1 | 12
F | 26 | 1 | 1 | 2
M | 26 | 6 |   | 6
F | 27 | 5 | 1 | 6
M | 27 | 2 |   | 2
F | 28 | 19 |   | 19
M | 28 | 10 | 2 | 12
F | 29 | 4 |   | 4
M | 29 | 1 |   | 1
F | 30 | 3 |   | 3
M | 30 | 3 | 1 | 4
F | 31 | 8 |   | 8
M | 31 | 12 | 1 | 13
F | 32 | 5 |   | 5
M | 32 | 3 |   | 3
F | 33 | 3 | 1 | 4
M | 33 | 2 | 2 | 4
F | 34 | 12 | 1 | 13
M | 34 | 4 | 1 | 5
F | 35 | 1 |   | 1
M | 35 | 2 |   | 2
F | 36 | 3 | 1 | 4
F | 37 | 6 |   | 6
M | 37 | 6 | 1 | 7
F | 38 | 1 |   | 1
M | 38 | 3 |   | 3
M | 39 | 1 |   | 1
F | 40 | 6 | 1 | 7
M | 40 | 2 | 2 | 4
F | 41 | 3 |   | 3
F | 42 | 2 |   | 2
M | 42 | 5 | 1 | 6
M | 43 |   | 1 | 1
F | 44 | 3 |   | 3
M | 44 | 1 |   | 1
F | 45 | 3 |   | 3
M | 45 | 2 |   | 2
F | 46 | 1 | 2 | 3
M | 46 | 2 | 1 | 3
M | 47 | 1 |   | 1
M | 48 |   | 1 | 1
