### ISSUE TITLE
Patient.communication.language sometimes contains invalid system

### ISSUE THREAD

**Issue by emesar** [synthetichealth/synthea#909]
Per the FHIR R4 spec for the Patient resource, the [Patient.communication.language](https://www.hl7.org/fhir/patient-definitions.html#Patient.communication.language) element has a "preferred" binding with the [Common Languages](https://www.hl7.org/fhir/valueset-languages.html) ValueSet, but a "required" binding with the [All Languages](https://www.hl7.org/fhir/valueset-all-languages.html) ValueSet. Both ValueSets use the following system URI exclusively: `urn:ietf:bcp:47`.

However, there are 5 languages provided in [Synthea's language lookup file](https://github.com/synthetichealth/synthea/blob/master/src/main/resources/language_lookup.json) which instead provide `http://id.loc.gov/vocabulary/iso639-1` as the system URI. An example generated by Synthea:

```json
"communication": [{
    "language": {
        "coding": [{
            "system": "http://id.loc.gov/vocabulary/iso639-1",
            "code": "vi",
            "display": "Vietnamese"
        }],
        "text": "Vietnamese"
    }
}]
```

Can these be changed to use the correct system URI (`urn:ietf:bcp:47`)?

**Comment by jawalonoski** [comment]
Technically bcp47 is not a Code System, it is a ValueSet.

It does not define any of its own codes, instead it includes codes from other systems, e.g. iso639-1 which defines the "vi" code (among others).

I don't care if we update the language lookup file so that FHIR validates (assuming that it will actually fix FHIR validation), but the `system` in that example is technically correct (and if FHIR says it is invalid, then FHIR is wrong).

Feel free to submit a pull request with the changes, and steps to verify the changes are correct and validate properly.

**Comment by emesar** [comment]
@jawalonoski thanks for the quick response. After researching this a bit further, I see your point; BCP-47 doesn't define the actual meaning of the various language codes, just a best practice structure.

FHIR is *definitely* treating BCP-47 as a CodeSystem, though; it's provided as such in the [HL7 Code System Registry](https://www.hl7.org/fhir/terminologies-systems.html).

I've asked for some clarity in the [FHIR Zulip](https://chat.fhir.org/#narrow/stream/179202-terminology/topic/BCP-47/near/244213266).

**Comment by jawalonoski** [comment]
Well, given the resolution over at FHIR Zulip, I'm happy to take a pull request to fix this issue if you want to make a contribution.

If we don't get one in a few days we'll get around to correcting it.

**Comment by jawalonoski** [comment]
Thank you for reporting the bug, investigating it, and fixing it!
