### ISSUE TITLE
Health records for a specific population

### ISSUE THREAD

**Issue by Mike2023** [synthetichealth/synthea#922]
Hi, I try to generate health records of a special population for research using Synthea with a customized file of demographics.csv.
However, there are no data for race, annual income, and education level.
Is it possible to leave those fields blank? I could use the default data for these fields but the default statistics won't represent the specific population well. 
If yes, what impacts on the results when doing this?

Appreciate!

Mike

**Comment by dehall** [comment]
These fields are required in demographics.csv, if not specified then the app will fail to load.

Race is a factor in the following modules (primarily affecting condition incidence/prevalence):
 - Anemia
 - Breast cancer
 - Cystic fibrosis
 - Gallstones
 - Metabolic syndrome
 - Self harm
 - SDoH screening
 - Hypertension medication

Income and education level are used to calculate Socioeconomic Status, which is a factor in the following modules:
- COPD
- Dementia (Alzheimer's)
- Homelessness
- Opioid Addiction

So if none of those are conditions of interest then the race/income/education fields can be filled fairly arbitrarily. Either way I'd suggest starting with the values from a real location, and then you can tweak from there if needed.

**Comment by Mike2023** [comment]
Thank you very much. We aim to create a synthetic population for flight pilots by Synthea no matter of specific disease module. 
Is it possible to add a career name in Synthea command or setting when generating a population. For example, career name: OCCP: 9030--TRN-Aircraft Pilots and Flight engineer  as specified at https://data.census.gov/mdat/#/search?ds=ACSPUMS5Y2019&rv=OCCP&nv=SOCP&wt=PWGTP.

Thanks a lot

**Comment by jawalonoski** [comment]
Synthea currently does not support named professions.

**Comment by Mike2023** [comment]
Thank you.

**Comment by Mike2023** [comment]
Is there a way to create a synthetic population of flight pilots using Synthea? We have a database of aeromedical certificate exams but lack of race, income and education.
Appreciate!

**Comment by jawalonoski** [comment]
> Is there a way to create a synthetic population of flight pilots using Synthea? 

Yes, but depending on the level of detail you want, it can be a small amount of work (for example, just specifying an age range and some demographic data and pretending that is your cohort of pilots) or a significantly large amount of work (for example, modeling the actual demographics statistics of pilots and modifying the disease modules to be more "pilot specific" if that is a concern).

> We have a database of aeromedical certificate exams but lack of race, income and education.

I'm not sure what you plan to do with the certificate exams, but if you don't have demographics you can either assume demographics from a state and filter on age, or see if you can get demographics for that particular job code from the Census Bureau [not sure if this is possible or not]) and make a custom demographics file.

**Comment by Mike2023** [comment]
Our database has gender, age and address only so we can get demographics of gender and age at locations.
The small amount of work would use the limited demographics data from our database and arbitrary data for other demographic fields, as I understand.

For the large amount of work, how to model the actual demographics statistics of pilots?
How to modify the disease modules to be more "pilot specific"?
Could you please have a rough estimate of workload because we need to plan it? 

Thanks a lot

**Comment by Mike2023** [comment]
I just got the demographics of flight pilots from Census Bureau, BTW.

**Comment by jawalonoski** [comment]
Engineering estimates are heavily dependent on the project objectives, the requirements, the trade-offs between cost/scope/schedule, the skills and expertise of the project team, and a myriad of other factors.

Therefore, it doesn't make a lot of sense for the Synthea project team to provide you with an estimate of how long it will take you.

It sounds like you have some unknowns and some risks, so in order to make an estimate, you should explore those unknowns and risks.

You can find information about modifying Synthea demographics here: https://github.com/synthetichealth/synthea/wiki/Demographics-for-Other-Areas

You can find information about building modules here: https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework and an example walk-through here: https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-Complete-Example

For how you might make modules pilot specific --- I do not have the expertise to answer that question. You should direct that question to a clinician.

**Comment by Mike2023** [comment]
Thank you.
