### ISSUE TITLE
social factors 

### ISSUE THREAD

**Issue by stephteeple** [synthetichealth/synthea#950]
Hello! Really appreciate all the work you guys do, Synthea is such an incredible open-source resource. 

I do research related to EHR data, healthcare delivery and health equity. I was thinking it might be interesting to potentially benchmark Synthea vs real EHR data in terms of heterogeneity in both health status and healthcare delivery related to social factors. 

I had two questions I was wondering if you could answer. I read through the recent SDOH updates, which look very cool - are there any additional updates related to SDOH/demographics on the horizon (e.g., addition to more modules)? Secondly, are there any particular conditions/interventions that you think would be most interesting to explore first? 

Happy to provide more detail if it'd be helpful - thank you!

**Comment by jawalonoski** [comment]
> I read through the recent SDOH updates, which look very cool - are there any additional updates related to SDOH/demographics on the horizon (e.g., addition to more modules)? 

We are very interested in continuing to add SDoH and modify the [disease modules](https://github.com/synthetichealth/synthea/wiki/Module-Gallery) so that those SDoH have more impact on health outcomes (i.e., either in the probabilities or conditional logic). However, we have no specific plans at the moment other than the general desire to move in that direction.

> Secondly, are there any particular conditions/interventions that you think would be most interesting to explore first?

Given that Synthea usually has a single standard of care implemented for each disease, or a single standard with a handful of subpaths/options, most of the conditions/interventions will look very similar, with one to three variations. I have no suggestions other than to do a literature review (others have done similar work, so you don't necessarily want to repeat their work) and focus on something that interests you.

**Comment by stephteeple** [comment]
Great, thanks!
