### ISSUE TITLE
Birth order and mother's maiden name

### ISSUE THREAD

**Issue by proxsys** [synthetichealth/synthea#999]
Is it possible to add birth order and mother's maiden name to the demographics of a patient?

**Comment by proxsys** [comment]
Thank you for your prompt reply.

I'm trying to figure out how to add it to the patients.csv output.

Birth order should be represented with an integer (1-9), calculated from the date/time of the birth date/time

**Comment by jawalonoski** [comment]
## Hints to Implement

First, you would add the field to the CSV headers:

https://github.com/synthetichealth/synthea/blob/17e5584c2d95894dfafd6de323ccfabf5642c56f/src/main/java/org/mitre/synthea/export/CSVExporter.java#L291-L294

Next, you would add the data to each record:

https://github.com/synthetichealth/synthea/blob/17e5584c2d95894dfafd6de323ccfabf5642c56f/src/main/java/org/mitre/synthea/export/CSVExporter.java#L557-L624

## The Problem

This should be fairly straight-forward for Mother's patient name: add `Person.NAME_MOTHER` to the list of exported fields.

Unfortunately, things get a little more complicated for birth order. That is because we do not simulate that level of detail, so each person does not have a birth order.

So, you have two choices.

1. Simulate birth order (the details of which are beyond the scope of this post)
2. Pick a birth order randomly from some non-uniform distribution.

**Comment by proxsys** [comment]
Thank you!  This has been very helpful to solve the problem and to understand Synthea a lot more.
